stages:
  - lint
  - build
  - artifacts

cache:
  paths:
  - node_modules/

lint.test:
  stage: lint
  script:
    - npm i
    - npm run lint
  tags:
    - pp-projects

build.develop:
  stage: build
  script:
    - cd /home/devuser/DevProjects/649.bridge/extension
    - git pull origin develop
    - npm i
    - npm run build-dev
  only:
    - develop
  environment:
    name: development
  tags:
    - pp-projects

artifacts.build:
  stage: artifacts
  script:
    - npm i
    - npm run build-ext
  artifacts:
    paths:
      - build/zip/echo_bridge.zip
  only:
    - develop
    - master
  tags:
    - pp-projects

build.master:
  stage: build
  script:
    - cd /home/devuser/Projects/649.bridge/extension
    - git pull origin master
    - npm install
    - npm run build-stage
  only:
    - master
  environment:
    name: stage
  tags:
    - pp-projects