language: node_js
node_js:
  - "10"

stages:
  - lint
  - test
  - build

jobs:
  include:

#    - stage: lint
#      name: "Lint"
#      if: type = push
#      script:
#        - npm run lint

    - stage: test
      name: "Tests"
      if: branch IN (develop, master) AND type = pull_request
      script: npm run test

    - stage: build
      env:
        - ARTIFACTS_KEY=$SPACE_KEY
        - ARTIFACTS_SECRET=$SPACE_SECRET
        - ARTIFACTS_BUCKET="bridge-extensions"
      name: "Build Artifacts"
      if: (branch = master OR tag IS present OR branch = ECHO-1113) AND type = push
      addons:
        artifacts:
          endpoint: https://fra1.digitaloceanspaces.com
          paths:
#            - build/zip/echo_bridge.zip
            - package.json
#
      script:
#        - npm run build-ext
        - npm run test
#      deploy:
#        debug: true
#        provider: s3
#        access_key_id: $SPACE_KEY
#        secret_access_key: $SPACE_SECRET
#        bucket: "bridge-extensions"
#        skip_cleanup: true
#        local_dir: examples
#        on:
#          branch: ECHO-1113
#        endpoint: https://fra1.digitaloceanspaces.com

#    - stage: deploy
#      name: "Deploy Develop"
#      if: type = push AND branch = ECHO-1113
#      script:
#        - ssh devuser@${DEV_SERVER} BRANCH=$CI_COMMIT_REF_NAME PROJECT=$CI_PROJECT_NAME 'bash -s' < ./deploy/update.sh
