language: node_js
node_js:
  - "10"

stages:
  - lint
  - test
  - build

jobs:
  include:

#    - stage: lint
#      name: "Lint"
#      if: type = push
#      script:
#        - npm run lint

    - stage: test
      name: "Tests"
      if: branch IN (develop, master) AND type = pull_request
      script: npm run test

    - stage: build
      name: "Build Artifacts"
      if: (branch = master OR tag IS present OR branch = ECHO-1113) AND type = push
      addons:
        artifacts:
          s3_region: "eu-central-1"
          paths:
            - build/zip/echo_bridge.zip
      script:
        - npm run build-ext
